# Generated by Django 5.0 on 2024-01-07 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coursereview',
            old_name='reviewer',
            new_name='user',
        ),
    ]
